add jjab and gitab auto-branch/auto-bookmark commands

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -344,6 +344,136 @@ function frg {
     fi
 }
 
+## jj auto bookmark
+##
+## Create a bookmark by taking the first line of the description and converting it
+jjab() {
+  local rev="$1"
+  if [[ -z $rev ]]; then
+    rev="@-"
+  fi
+  local newname=$(jj log -r "$rev" --no-graph -n1 -T 'description.first_line()' \
+    | sed -Ee 's/[^a-zA-Z1-9]+/_/g' \
+    | sed -Ee 's/^_+|_+$//g' \
+    | tr '[:upper:]' '[:lower:]'
+  )
+  local mark="bwm/$newname"
+  jj bookmark create "$mark" -r "$rev"
+
+  local cmd=(jj git push --allow-new -b $mark)
+  local oldhist=""
+  local resethist=false
+  if [[ -n "${ZSH_AUTOSUGGEST_HISTORY_IGNORE:-}" ]]; then
+    oldhist="${ZSH_AUTOSUGGEST_HISTORY_IGNORE}"
+    resethist=true
+  fi
+
+  ZSH_AUTOSUGGEST_HISTORY_IGNORE=*
+
+  local doit
+  vared \
+    -p "jjab: push new bookmark to forge? [y/N] " \
+    -r "${cmd[*]}" \
+    doit
+
+  if $resethist ; then
+    ZSH_AUTOSUGGEST_HISTORY_IGNORE="$oldhist"
+  else
+    unset ZSH_AUTOSUGGEST_HISTORY_IGNORE
+  fi
+
+  if [[ $doit =~ ^y ]]; then
+    echo "> ${cmd[*]}"
+    local outfile=$(mktemp --tmpdir jjab.out.XXXXXXXXXX)
+    ${cmd[@]} > $outfile 2>&1
+    cat $outfile
+    local pr_url=$(grep -Eo 'https://github.com/.*pull/new[^ ]*' $outfile)
+    rm "$outfile"
+    if [[ -n "$pr_url" ]]; then
+      python3 -m webbrowser "$pr_url"
+    else
+      echo "jjab: No PR URL found"
+    fi
+  else
+    echo "${cmd[*]}" | wtcopy
+    echo "jjab: bokmark push command is in your clipboard"
+  fi
+}
+
+## git auto branch
+##
+## Create a branch from <rev> using the first line of the commit message
+## (lowercased with non-alnum -> "_"), then push and open/create a PR.
+gitab() {
+  local rev="${1:-HEAD}"
+
+  local newname
+  newname=$(git show -s --format=%s "$rev" \
+    | sed -Ee 's/[^a-zA-Z0-9]+/_/g' \
+    | tr '[:upper:]' '[:lower:]' \
+    | sed -Ee 's/^_+|_+$//g'
+  )
+
+  if [[ -z "$newname" ]]; then
+    echo "gitab: could not derive a name from commit subject for rev: $rev" >&2
+    return 1
+  fi
+
+  local branch="bwm/$newname"
+
+  if ! git rev-parse --quiet --verify "$branch" >/dev/null; then
+    git branch "$branch" "$rev"
+    echo "gitab: created $branch on $rev"
+  fi
+
+  local cmd=(git push -u origin "$branch")
+  local doit
+
+  local oldhist=""
+  local resethist=false
+  if [[ -n "${ZSH_AUTOSUGGEST_HISTORY_IGNORE:-}" ]]; then
+    oldhist="${ZSH_AUTOSUGGEST_HISTORY_IGNORE}"
+    resethist=true
+  fi
+
+  ZSH_AUTOSUGGEST_HISTORY_IGNORE=*
+
+  vared \
+    -p "gitab: push new branch & create PR? [y/N] " \
+    -r "${(j: :)cmd}" \
+    doit
+
+  if $resethist ; then
+    ZSH_AUTOSUGGEST_HISTORY_IGNORE="$oldhist"
+  else
+    unset ZSH_AUTOSUGGEST_HISTORY_IGNORE
+  fi
+
+  if [[ "$doit" =~ ^[yY] ]]; then
+    echo "> ${cmd[*]}"
+
+    local outfile
+    outfile=$(mktemp -t gitab.out.XXXXXXXXXX)
+
+    "${cmd[@]}" >"$outfile" 2>&1
+
+    cat "$outfile"
+    local pr_url=$(grep -Eo 'https://github.com/.*pull/new[^ ]*' $outfile)
+    rm "$outfile"
+    if [[ -n "$pr_url" ]]; then
+        python3 -m webbrowser "$pr_url"
+    else
+        echo "gitab: No PR URL found"
+    fi
+  else
+    # Put the push + PR command in clipboard (best-effort)
+    local tocopy="git push -u origin $branch"
+    print -r -- "$tocopy" | wtcopy
+    echo "gitab: branch/PR command is in your clipboard"
+  fi
+}
+
+
 # Vterm stuff, tells emacs which directory we're currently in
 vterm_printf() {
     if [ -n "$TMUX" ]; then
